Month 10/step 1
evgsamalex/react-burger pull request #8
Opened 2022-12-06 15:05 UTC by evgsamalex

2022-12-06 16:12 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Ваш проект теперь полностью типизирован 🔥

### **Но есть несколько замечаний, которые нужно исправить (некоторые замечания отмечены в коде):**

- В ленте заказов должна быть подсчитано полная стоимость заказа: https://yadi.sk/d/6VsTLFXMP-JJpQ;

- `burger-constructor` - также нужно типизировать.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статья по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-06 16:12 UTC, ArslanMustafin commented on src/api/rest/auth/login.ts
> +    method: RequestMethod.Post,
**Вы молодец:**

Круто что используйте `enum`;

2022-12-06 16:12 UTC, ArslanMustafin commented on src/api/rest/auth/login.ts
> +    method: RequestMethod.Post,
**Можно лучше:**

Я бы пошёл чуточку дальше, и это бы тоже вынес в какой-то объект, в виде константы))

2022-12-06 16:12 UTC, ArslanMustafin commented on src/api/storage/token-storage.ts
> +  return token ? token : '';
**Можно лучше:**

Лучше использовать оператор или - `||`

2022-12-06 16:12 UTC, ArslanMustafin commented on src/api/config.ts
>  const wsPrivateUrl = "wss://norma.nomoreparties.space/orders"
**Надо исправить**

имена констант принято записывать в стиле UPPER_CASE

2022-12-06 16:12 UTC, ArslanMustafin commented on src/api/index.ts
> +export interface IApi {
**Можно лучше:**

т.к мы тут просто используем typeof, то задумайтесь нужен ли действительно этот тип, возможно лучше будет без него, т.к. типы с функций сами подтянутся.

2022-12-06 16:12 UTC, ArslanMustafin commented on src/api/sendRequest.ts
> +}
**Можно лучше:**

Не совсем понял причину использования тут структуры данных.

2022-12-06 16:12 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor-ingredient.tsx
> +const BurgerConstructorIngredient: FC<{ ingredient: TBurgerConstructorItem }> = ({ingredient}) => {
**Можно лучше:**

я бы вынес это в отдельный тип, чтобы в случае чего можно было бы добавлять туда параметры.

2022-12-06 16:12 UTC, ArslanMustafin commented on src/components/burger-ingredient/burger-ingredient.tsx
>    console.log('render ingredient')
**Надо исправить:**

В приложении не должно быть, консоль логов, или дебаггеров))

2022-12-06 16:12 UTC, ArslanMustafin commented on src/utils/utils.ts
> +export const delay = (ms: number) => new Promise(res => setTimeout(res, ms))
**Можно лучше:** 

вроде бы это нигде не используется.

2022-12-07 07:59 UTC, evgsamalex commented on src/api/sendRequest.ts
> +}
я хотел управлять токеном в одном месте, но не осилил пока перехватчики. Не хотел разбрасывать обновление и проверку токена по разным частям кода. Реализация пока так себе. Но еще хочу подумать как лучше. Т.е тут у меня не совсем API, а больше на SDK похоже с внутренней логикой.

2022-12-07 08:01 UTC, evgsamalex commented on src/utils/utils.ts
> +export const delay = (ms: number) => new Promise(res => setTimeout(res, ms))
не хочется добавлять и убирать. я использовал для проверки отрисовки загрузки данных пока стоит фладок isLoading.

2022-12-07 16:10 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

- Все замечания с прошлого ревью были исправлены. 🔥

### **Желательно исправить:**

- Еще раз проверьте приложения на console.log. https://yadi.sk/d/FBJDPSHxCZNYEw

2022-12-08 13:33 UTC, merged